name: TRML Daily Update

on:
  schedule:
    - cron: "10 0 * * *"   # каждый день в 00:10 UTC
  workflow_dispatch:         # кнопка Run workflow вручную

permissions:
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        working-directory: SITE-trml/TRML-base
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run TRML backend
        working-directory: SITE-trml/TRML-base
        run: |
          python trml_base.py

      - name: Commit updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add SITE-trml/assets/trml-latest.json SITE-trml/assets/trml-history.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: daily TRML index update"
          git push
